name: Lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # The type of runner that the job will run on
    name: Run Lint and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          # no support for lts as of now with github actions.
          # issue link : https://github.com/actions/setup-node/issues/26
          node-version: "14"

      - name: Npm install
        run: npm i

      - name: Run lint Prettier
        run: npx prettier --check .

      - name: Run lint Eslint
        run: eslint .

      - name: Run build
        run: npm run build
